### ISSUE TITLE
CTRL + doesn't work for zooming in on certain keyboard layouts

### ISSUE THREAD

**Issue by mathiashusted** [lainsce/aesop#11]
Hi!

I'd like to let you know that the key command **CTRL** + **+** (pressing '+' while holding CTRL) for zooming in doesn't work on keyboard layouts where the '+' key is to the right of the '0' key. These layouts include:
- Danish
- Swedish
- Norwegian
- Estonian

Pressing the key corresponding to the '+' key on the US layout does work on the layouts mentioned above, though - despite not being the actual '+' key.

**Comment by lainsce** [comment]
That's a bug with how programmed keybinds in GTK3 work, it should also affect other apps as well.

**Comment by alcinnz** [comment]
I'm not sure if it'll correct those layouts, but on some keyboards `+` is `<shift>=`. So in Odysseus I have a second binding for that combination which also zooms in.

In case it helps.

**Comment by lainsce** [comment]
Will try that out :)

**Comment by lainsce** [comment]
Fixed in `master`, will release soon.

**Comment by mathiashusted** [comment]
Awesome!
