### ISSUE TITLE
Feature request: automatic PDF updating

### ISSUE THREAD

**Issue by conruggles** [lainsce/aesop#12]
It would be really nice to have Aesop detect changes to a PDF and then display the new PDF, like evince does. When you're working on a Markdown or Latex document and have it autocompile to a PDF on save, it's really nice to have that open to the side so I can see the changes in real time. I would assume this would involve adding a daemon or some background process checking for changes to the last time modified of the file, and if there are any, reload the file.

Let me know if you need any help developing this feature, I might be able to provide some. Thanks!

**Comment by lainsce** [comment]
That's a good feature, I'm gonna work on it soon.

**Comment by lainsce** [comment]
Fixed in `master`, coming shortly to you.
