### ISSUE TITLE
Freezes when opening Large PDF Files (200 Pages or more)

### ISSUE THREAD

**Issue by kid101** [lainsce/aesop#13]
The app is able to open the PDF but freezes when trying to maximize or go to the fullscreen mode.
The page change from 1 to 2 also happens very slowly, I need to wait for around 10 Secs to move on to the next page.

I'm on elementary OS Juno Release

**Comment by lainsce** [comment]
I'll try doing a fix soon but no promises since PDF handling is a mystery.

**Comment by lainsce** [comment]
Working on this

**Comment by lainsce** [comment]
Fixed in master.
