### ISSUE TITLE
Need help before translating

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#15]
@lainsce please can you check if translations files are up to date ? If they are I can translate the app to French. Please also check that you added the `appdata.xml` strings to  translations files :+1:

**Comment by lainsce** [comment]
Please read my comment at: https://github.com/lainsce/palaura/issues/27

Yes, all files are up-to-date.

**Comment by NathanBnm** [comment]
So I will add French translation soon :+1:
