### ISSUE TITLE
Some actions aren't working + Translations

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#17]
Actually I tried to open a PDF but I wasn't able to scroll, there is no scroll bar at all, and the page selector doesn't work either.

Also the full-screen button doesn't work.

Finally some translations (in AppCenter as reported for Yishu), and for the "No PDF file open" and titles on header bar buttons (like "Light background" and "Dark background" for example, or "Open") seems not to work.

**Comment by lainsce** [comment]
Will fix these

**Comment by lainsce** [comment]
Update Report: What you complained about there being no scroll bar, is because the PDF scrolls with the mouse wheel. As for the full screen bug and those translation bugs, those are bugs.

**Comment by lainsce** [comment]
Fixed both in master.
