### ISSUE TITLE
Printing with dark mode on results in an all-black print

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/aesop#2]
Something is weird when printing with the colors inverted. I'd imagine printing shouldn't invert the colors/should always do black-on-white.

_Version 1.0.0_

**Comment by lainsce** [comment]
I wrote it so that if the pdf is seen inverted, it inverts the print also. Kind of a weird quirk.

**Comment by lainsce** [comment]
Will remove this quirk for 1.0.1

**Comment by lainsce** [comment]
Fixed in `master`
