### ISSUE TITLE
Dark background should be applied to tha app too

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#20]
Currently it's only applied on the PDF itself

**Comment by lainsce** [comment]
I made it this way to retain the app's branding, because it'd get muddy with the dark stylesheet.

**Comment by NathanBnm** [comment]
What do you mean? You should take a look at https://github.com/rkoesters/xkcd-gtk

**Comment by lainsce** [comment]
I mean I'd get loss of contrast with the beige background and then, the white text and icons on top. And that's a no-no.

**Comment by lainsce** [comment]
Closing issue as stale for 20+ days have passed without a good enough UX solution for this.
