### ISSUE TITLE
PDF images are reverted with dark background

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#21]
Is there any way to avoid transformation on coloured images ?

Here is an example:

![image](https://user-images.githubusercontent.com/45366162/57178141-9eb9a280-6e6c-11e9-8fab-8a1333d0e326.png)

**Comment by lainsce** [comment]
Sadly there's not much I can do with this as PDFs are a closed box, and I can't modify the PDF to be true dark mode unless I use inverted colors. Sorry but this is unfixable.

**Comment by NathanBnm** [comment]
> Sadly there's not much I can do with this as PDFs are a closed box, and I can't modify the PDF to be true dark mode unless I use inverted colors. Sorry but this is unfixable.

I kind of suspected that.

**Comment by lainsce** [comment]
Closing issue as stale for 20+ days have passed without new comments on this.
