### ISSUE TITLE
First zoom is making pagination messy

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#23]
When I zoom for the first time on a document, it makes it back to the first page, but the pagination stay at it's previous state. It does not happen every time, I'll will complete with screenshots if it appears again.

**Comment by lainsce** [comment]
This is strange. Awaiting screenshots. :smile:

**Comment by NathanBnm** [comment]
For now I cannot repeat the issue.

**Comment by lainsce** [comment]
Closing issue as stale for 20+ days have passed without confirmation of same occurrence.
