### ISSUE TITLE
Aesop start pagination issue

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#24]
When I start Aesop again, it remembers the last opened document but it show the last page of it and the pagination is at 1. But when I change the pagination it shows the first page back and become normal again.

Here are some screenshots:

First time I open a document (on first page):
![image](https://user-images.githubusercontent.com/45366162/57178266-045a5e80-6e6e-11e9-936e-f0257308e81d.png)

Then I close the app and reopen it:

It shows me the last page of the document with pagination "1":
![image](https://user-images.githubusercontent.com/45366162/57178287-27850e00-6e6e-11e9-86a3-a46710d71ab0.png)

And when I go to page 2, it really goes to page 2 (from the last page to page 2):
![image](https://user-images.githubusercontent.com/45366162/57178293-3bc90b00-6e6e-11e9-902d-7fcd31e7c967.png)

**Comment by lainsce** [comment]
I'll see what I can do.

**Comment by lainsce** [comment]
Fixed :tada:
