### ISSUE TITLE
Issue with fullscreen button

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#28]
Maybe this issue could be related to zoom level (#22).

Here is a GIF:

https://imgur.com/a/fNgzWRI

**Comment by lainsce** [comment]
Yeah, I don't really know how to fix this one. I'm torn between just letting it be vs. removing the button but let people only maximize via key shortcut.

**Comment by NathanBnm** [comment]
If it doesn't work, I think you should remove it, even temporarily. There is the same issue with your app Planning.

**Comment by lainsce** [comment]
Then I'll remove it and make a keyboard shortcut to make it fullscreen. :+1: 
Also, Planning? Not by me, I guess? I have only Yishu and Timetable.

**Comment by NathanBnm** [comment]
Sorry I mentionned the name in French I am talking about Timetable!

**Comment by lainsce** [comment]
I couldn't have a shortcut for this, but I removed the button, and now the bug doesn't happen.
