### ISSUE TITLE
PDFs look blurry on High-DPI / retina display

### ISSUE THREAD

**Issue by gka** [lainsce/aesop#3]
I wish I could read properly my PDFs, but they look blurry on my HiDPI monitor.

**Comment by lainsce** [comment]
That's due to using the Cairo graphics framework to display pages. Also I don't have any means of developing for HiDPI due to not having a monitor with it. :pensive:

**Comment by lainsce** [comment]
Closing issue because I don't have the means of solving this issue with my current monitor. :disappointed:
