### ISSUE TITLE
App unable to start

### ISSUE THREAD

**Issue by colintanlk** [lainsce/aesop#37]
## Hello! If you found an error in this app, follow this template:

 dconf-CRITICAL **: 06:58:07.738: unable to create file '/run/user/1000/dconf/user': Too many open files.  dconf will not work properly.

Latest version on Aesop and Elementary

**Comment by lainsce** [comment]
This seems like an outside problem to me. Never occurred to me while testing. I recommend researching how to reset dconf things.
