### ISSUE TITLE
The App Won't Open

### ISSUE THREAD

**Issue by Fatih20** [lainsce/aesop#38]
The app would just show up on the dock but no windows would actually be opened, regardless if you open it from the appcenter or the applications menu. After doing that, it would just close itself after a few seconds.

**Comment by lainsce** [comment]
Try resetting the dconf settings of the app:
`dconf reset -f /com/github/lainsce/aesop`
and tell me if it works then.

**Comment by Fatih20** [comment]
Nope, still doesn't work.

**Comment by lainsce** [comment]
I'll look into it then.

**Comment by lainsce** [comment]
I can't make it not open, so, must be something external, friend...

**Comment by Fatih20** [comment]
Perhaps there are libraries not being installed? But it should've installed all necessary libraries when installed from the appcenter, right?

**Comment by lainsce** [comment]
Or something went wrong with the installation, something must've been blocked if you added PPAs or modified things like that.
