### ISSUE TITLE
Aesop fails to start [crash]

### ISSUE THREAD

**Issue by janxkoci** [lainsce/aesop#39]
I installed Aesop moments ago, using AppCenter, but it fails to open. Opening it from terminal prints a lot of vala errors and dconf critical errors, complaining about exceeded limit of opened files. Then it segfaults.

I'm attaching the terminal output (parts of the error messages are in czech language, sorry) and a coredump:

[aesop-coredump.txt](https://github.com/lainsce/aesop/files/4268218/aesop-coredump.txt)
[aesop-terminal.txt](https://github.com/lainsce/aesop/files/4268219/aesop-terminal.txt)

I have the latest available version - `1.2.3`.

**Comment by lainsce** [comment]
This doesn't look like something I can help with, I never touch `/run/user/1000/dconf` nor do I know what that is. I also can't help with this as it seems like a dconf related issue, Aesop works here no crashes.

**Comment by lainsce** [comment]
Found the source of the crash: It happens after one opens a PDF and reopens Aesop.

**Comment by lainsce** [comment]
Should be fixed now. Closing...

**Comment by janxkoci** [comment]
It actually also crashed right after installation, when I clicked the "open" button in AppCenter. But it works now, so it's ok.
