### ISSUE TITLE
Only a single page of certain PDFs renders

### ISSUE THREAD

**Issue by alcinnz** [lainsce/aesop#4]
If I open the attached PDF in Aesop 1.0.2 it shows only one page of it, but if I open it in GNOME Document Viewer I see all 7 pages of it.

I expect to see all y pages in Aesop. 

[CACM86.pdf](https://github.com/lainsce/aesop/files/2139254/CACM86.pdf)

**Comment by alcinnz** [comment]
To expand some more, I did try using the spinner to switch between pages, which didn't work for the given PDF. And for a separate 46 page PDF, it only let me navigate until page 7.

**Comment by lainsce** [comment]
Somehow, by scrolling, I could get to all 7 pages of `CACM86.pdf` but I think that this particular pdf has many custom fonts or something so it's taxing on CPU, hence looking like it doesn't open properly at first glance. I did see that the spinnerbox isn't actually updating properly here.

Not all PDFs are created equally, so if somehow this one has proprietary PDF stuff, it will hang Aesop up, and I can't do anything there.

**Comment by lainsce** [comment]
Fixed in 1.0.3
