### ISSUE TITLE
[wishlist] Consider supporting contractors

### ISSUE THREAD

**Issue by janxkoci** [lainsce/aesop#40]
Consider supporting [contractors](https://elementary.io/docs/human-interface-guidelines#contractor) - this would allow integration with other apps. For example, a selected word in a document could be looked up in Palaura or other compatible dictionary.

**Comment by lainsce** [comment]
I think contractors only add more complexity to a system of mimetype registration already done in-app; if you have Aesop set as the PDF handler, it'll do just the same.
As for Palaura, it's finicky to do that because only so many apps have contractor enabled.

**Comment by janxkoci** [comment]
Yeah I meant that you could add contractor into both Aesop and Palaura to make them work better together (with the example use-case of looking up words from open document in a dictionary), because you have both apps under your control, as their developer.

But I understand if you don't like the idea. It occurred to me when using Mac at work - in Preview.app you can lookup selected words using various sources (I think it uses Spotlight or something).

Anyway, I stopped using Aesop, as it doesn't even have zoom and the page browsing was rather cumbersome. So no biggie.
