### ISSUE TITLE
Unable to maximize window

### ISSUE THREAD

**Issue by Tataarujin** [lainsce/aesop#41]
Or, to be exact, there is no "Maximize" window control at all. Why is that?

## Hello! If you found an error in this app, follow this template:

* Use a descriptive title
* Describe the issue
* State what version you're using
* Take a screenshot of the problem, then use the Markdown property for it:  
   `![any_name_here](url_here)`
* If the problem needs it, show me a video of the problem with Screenkey running in the background.

Thanks!

**Comment by lainsce** [comment]
I'm in the middle of reworking the UI, and maximization will be part of it.

**Comment by lainsce** [comment]
Fixed, next release will have it.
