### ISSUE TITLE
Maximize button isn't working

### ISSUE THREAD

**Issue by btd1337** [lainsce/aesop#5]
Maximize button isn't working when a pdf file is open.

version: 1.0.1

I'm in elementary OS Juno Beta

**Comment by lainsce** [comment]
I'm gonna need more than that to understand your issue.

What's your screen size, things like that.

**Comment by btd1337** [comment]
My screen is 1366x768.

The application opens using for example 300x400. I want to use the fullscreen, so I click the maximize button, but this does not work.

**Comment by lainsce** [comment]
I'll see what I can do.

**Comment by lainsce** [comment]
Fixed in 1.0.3
