### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [lainsce/aesop#7]
@lainsce I will support your application in Arch Linux.

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find Aesop under the name [aesop-git](https://aur.archlinux.org/packages/aesop-git/) in the **AUR**:

`$ aurman -S aesop-git`

**Comment by lainsce** [comment]
Would you mind if I suggest `pikaur` tool instead? I'm more familiar with that one.

**Comment by btd1337** [comment]
The problem is not with me, but for suggesting a tool with many vulnerabilities that is not recommended by the system developers and the AUR maintainers.

It's as if we suggest you use something that has breaches of vulnerability. This is not good.

But it's a private decision since you own this repository and has this preference.

If I could choose, it would be for one of these that are on the list.

![screenshot from 2018-07-04 23-51-27](https://user-images.githubusercontent.com/11943860/42300118-348532a6-7fe5-11e8-8df3-ea69ab2a60a8.png)

**Comment by btd1337** [comment]
I have just verified that Pikaur does not receive an update as soon as it is posted to the Github repository.

Other Aur helpers provide this functionality which is very important for a -git package.

**Comment by lainsce** [comment]
As I said before, I'm not forcing people to use pikaur, I know there's lots of AUR Helpers. If a person wants to they can just use their preferred AUR helper.
