### ISSUE TITLE
Make page_button insensitive on welcome view

### ISSUE THREAD

**Issue by worldofpeace** [lainsce/aesop#8]
### Description
 On the welcome view (when no pdf has been opened) it doesn't make sense for someone to be able to interact with the button because they're no pages to change.

Here's the [HIG](https://github.com/elementary/website/blob/master/docs/human-interface-guidelines.md#sensitivity-sensitivity) for reference.

**Comment by lainsce** [comment]
Will fix this as soon as possible

**Comment by worldofpeace** [comment]
@lainsce Great :+1:

**Comment by lainsce** [comment]
Fixed! Expect it in the next release!
